/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import MODELO.queryEmpleados;
import MODELO.queryProductos;
import MODELO.queryProveedores;
import VistaEmpleado.DatosEmpleados;
import VistaEmpleado.EmpleadoPrincipal;
import VistaEmpleado.EmpleadoPrincipal1;
import VistaProveedor.ProveedorPrincipal;
import VistaProveedor.ProveedorPrincipal1;
import VistasArticulos.BusquedaArticulos;
import VistasArticulos.ArticulosDelete;
import VistasArticulos.ArticulosNew;
import VistasArticulos.ArticulosUpdate;
import VistasClientes.ClienteSearch;
import VistasFamilia.FamiliasBuscar;
import VistasFamilia.FamiliasNew;
import VistasFamilia.FamiliasUpdate;
import VistasIva.IvaEditar;
import VistasIva.IvaLeer;
import VistasIva.IvaNew;
import VistasUsuarios.UsuariosCuenta;
import VistasUsuarios.UsuariosDelete;
import VistasUsuarios.UsuariosEdit;
import VistasUsuarios.UsuariosNew;
import VistasUsuarios.UsuariosSearch;
import VistasVentas.VentasNew;
import VistasVentas.VentasView;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.io.FileOutputStream;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;

/**
 *
 * @author rogerluje
 */
public class HomeAplicativo extends javax.swing.JFrame {

    /**
     * Creates new form HomeAplicativo
     */
    private static String cuenta;
    private static String nivel;

    public HomeAplicativo() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        Habilitar();
        lblCuenta.setVisible(true);
        lblNivel.setVisible(false);
    }

    public static JLabel getLblCuenta() {
        return lblCuenta;
    }

    public static void setLblCuenta(JLabel lblCuenta) {
        HomeAplicativo.lblCuenta = lblCuenta;
    }
    
    
    
    public HomeAplicativo(String aux) {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        lblNivel.setText(aux);
        Habilitar();
        lblCuenta.setVisible(true);
        lblNivel.setVisible(false);
    }
    public static boolean Cerrado(Object obj) {
        JInternalFrame[] activos = escritorio.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] == obj) {
                cerrado = false;
            }
            i++;
        }
        return cerrado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblCuenta = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jInicio = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jUsuarios = new javax.swing.JMenu();
        jClientes = new javax.swing.JMenuItem();
        jEmpleados = new javax.swing.JMenuItem();
        jProveedores = new javax.swing.JMenuItem();
        mbUsuarios = new javax.swing.JMenu();
        mAgregar3 = new javax.swing.JMenuItem();
        mModificar3 = new javax.swing.JMenuItem();
        mEliminar3 = new javax.swing.JMenuItem();
        mConsultar3 = new javax.swing.JMenuItem();
        jProductos = new javax.swing.JMenu();
        prodAgregar = new javax.swing.JMenuItem();
        prodModificar = new javax.swing.JMenuItem();
        prodConsultar = new javax.swing.JMenuItem();
        jVentas = new javax.swing.JMenu();
        venNueva = new javax.swing.JMenuItem();
        jInventarios = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jReportes = new javax.swing.JMenu();
        rptEmpleados = new javax.swing.JMenuItem();
        rptProveedores = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jConfiguracion = new javax.swing.JMenu();
        Ivas = new javax.swing.JMenu();
        IvaNew = new javax.swing.JMenuItem();
        IvaEdit = new javax.swing.JMenuItem();
        IvaSearch = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        FamiNew = new javax.swing.JMenuItem();
        FamiEdit = new javax.swing.JMenuItem();
        FamiSearch = new javax.swing.JMenuItem();
        Cuenta = new javax.swing.JMenuItem();
        jAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(65, 105, 170));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblCuenta.setForeground(new java.awt.Color(255, 255, 255));

        escritorio.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblCuenta, javax.swing.JLayeredPane.DEFAULT_LAYER);
        escritorio.setLayer(lblNivel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(824, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addComponent(lblCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, escritorioLayout.createSequentialGroup()
                        .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(escritorioLayout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(lblCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(828, Short.MAX_VALUE))
        );

        jMenuBar1.setAlignmentX(0.0F);
        jMenuBar1.setMaximumSize(new java.awt.Dimension(350, 250));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(350, 250));

        jInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/casa.png"))); // NOI18N
        jInicio.setText("Inicio");

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/apagar.png"))); // NOI18N
        jMenuItem21.setText("Cerrar Sesión");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jInicio.add(jMenuItem21);

        jMenuBar1.add(jInicio);

        jUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/equipo.png"))); // NOI18N
        jUsuarios.setText("Personal");

        jClientes.setText("Clientes");
        jClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientesActionPerformed(evt);
            }
        });
        jUsuarios.add(jClientes);

        jEmpleados.setText("Empleados");
        jEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmpleadosActionPerformed(evt);
            }
        });
        jUsuarios.add(jEmpleados);

        jProveedores.setText("Proveedores");
        jProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jProveedoresActionPerformed(evt);
            }
        });
        jUsuarios.add(jProveedores);

        mbUsuarios.setText("Usuarios");

        mAgregar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar-usuario.png"))); // NOI18N
        mAgregar3.setText("Agregar");
        mAgregar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAgregar3ActionPerformed(evt);
            }
        });
        mbUsuarios.add(mAgregar3);

        mModificar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar-usuario.png"))); // NOI18N
        mModificar3.setText("Modificar");
        mModificar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mModificar3ActionPerformed(evt);
            }
        });
        mbUsuarios.add(mModificar3);

        mEliminar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/eliminar-usuario.png"))); // NOI18N
        mEliminar3.setText("Eliminar");
        mEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEliminar3ActionPerformed(evt);
            }
        });
        mbUsuarios.add(mEliminar3);

        mConsultar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lista-de-usuario.png"))); // NOI18N
        mConsultar3.setText("Consultar");
        mConsultar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultar3ActionPerformed(evt);
            }
        });
        mbUsuarios.add(mConsultar3);

        jUsuarios.add(mbUsuarios);

        jMenuBar1.add(jUsuarios);

        jProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/carro.png"))); // NOI18N
        jProductos.setText("Productos");

        prodAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agrega-producto.png"))); // NOI18N
        prodAgregar.setText("Agregar");
        prodAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodAgregarActionPerformed(evt);
            }
        });
        jProductos.add(prodAgregar);

        prodModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar-producto.png"))); // NOI18N
        prodModificar.setText("Modificar");
        prodModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodModificarActionPerformed(evt);
            }
        });
        jProductos.add(prodModificar);

        prodConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ver-producto.png"))); // NOI18N
        prodConsultar.setText("Consultar");
        prodConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodConsultarActionPerformed(evt);
            }
        });
        jProductos.add(prodConsultar);

        jMenuBar1.add(jProductos);

        jVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/bolsa.png"))); // NOI18N
        jVentas.setText("Ventas");

        venNueva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nueva-venta.png"))); // NOI18N
        venNueva.setText("Nuevas Ventas");
        venNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                venNuevaActionPerformed(evt);
            }
        });
        jVentas.add(venNueva);

        jMenuBar1.add(jVentas);

        jInventarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/inventarios.png"))); // NOI18N
        jInventarios.setText("Inventarios");

        jMenuItem1.setText("Reportes de Ventas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jInventarios.add(jMenuItem1);

        jMenuBar1.add(jInventarios);

        jReportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/reportes.png"))); // NOI18N
        jReportes.setText("Reportes");

        rptEmpleados.setText("Empleados");
        rptEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptEmpleadosActionPerformed(evt);
            }
        });
        jReportes.add(rptEmpleados);

        rptProveedores.setText("Proveedores");
        rptProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptProveedoresActionPerformed(evt);
            }
        });
        jReportes.add(rptProveedores);

        jMenu1.setText("Productos");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/masVen.png"))); // NOI18N
        jMenuItem3.setText("Mas Vendidos");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/menosVen.png"))); // NOI18N
        jMenuItem2.setText("Menos Vendidos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jReportes.add(jMenu1);

        jMenuBar1.add(jReportes);

        jConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ajustes.png"))); // NOI18N
        jConfiguracion.setText("Configuracion");

        Ivas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/punto-de-venta.png"))); // NOI18N
        Ivas.setText("Ivas");

        IvaNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/insertarproducto.png"))); // NOI18N
        IvaNew.setText("Nuevo");
        IvaNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IvaNewActionPerformed(evt);
            }
        });
        Ivas.add(IvaNew);

        IvaEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/editar.png"))); // NOI18N
        IvaEdit.setText("Editar");
        IvaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IvaEditActionPerformed(evt);
            }
        });
        Ivas.add(IvaEdit);

        IvaSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nueva-venta.png"))); // NOI18N
        IvaSearch.setText("Consultar");
        IvaSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IvaSearchActionPerformed(evt);
            }
        });
        Ivas.add(IvaSearch);
        Ivas.add(jSeparator1);

        FamiNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar-documento-simbolo-delineado.png"))); // NOI18N
        FamiNew.setText("Familia Nueva");
        FamiNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamiNewActionPerformed(evt);
            }
        });
        Ivas.add(FamiNew);

        FamiEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/actualizar.jpg"))); // NOI18N
        FamiEdit.setText("Familia Editar");
        FamiEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamiEditActionPerformed(evt);
            }
        });
        Ivas.add(FamiEdit);

        FamiSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lista-de-usuario.png"))); // NOI18N
        FamiSearch.setText("Familia Consultar");
        FamiSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FamiSearchActionPerformed(evt);
            }
        });
        Ivas.add(FamiSearch);

        jConfiguracion.add(Ivas);

        Cuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ingresar.png"))); // NOI18N
        Cuenta.setText("Cuenta");
        Cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuentaActionPerformed(evt);
            }
        });
        jConfiguracion.add(Cuenta);

        jAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/equipo.png"))); // NOI18N
        jAcercaDe.setText("Acerca de");
        jAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAcercaDeActionPerformed(evt);
            }
        });
        jConfiguracion.add(jAcercaDe);

        jMenuBar1.add(jConfiguracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
EmpleadoPrincipal1 empleadoPrincipal;
    ProveedorPrincipal1 principal1;
    private void jEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmpleadosActionPerformed
        if (Cerrado(empleadoPrincipal)) {
            empleadoPrincipal = new EmpleadoPrincipal1();
            escritorio.add(empleadoPrincipal);
            //Para centrar la ventana abierta
            Dimension dimension = escritorio.getSize();
            Dimension FrameSize = empleadoPrincipal.getSize();
            empleadoPrincipal.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
            //
            empleadoPrincipal.show();
        }
    }//GEN-LAST:event_jEmpleadosActionPerformed
    public void Habilitar() {
        String aux = lblNivel.getText();
        System.out.println("nivel "+aux );
        switch (aux) {
            case "1":
                //Administrador
                System.out.println("Admin");
                break;
            case "2":
                //Empleado
                jEmpleados.setVisible(false);
                mbUsuarios.setVisible(false);
                System.out.println("Empleado");
                break;
            case "3":
                //Bodeguero
                jVentas.setVisible(false);
                System.out.println("Bodegero");
                break;
            default:
                break;
        }
    }
    private void jProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jProveedoresActionPerformed

        if (Cerrado(principal1)) {
            principal1 = new ProveedorPrincipal1();
            escritorio.add(principal1);
            Dimension dimension = escritorio.getSize();
            Dimension FrameSize = principal1.getSize();
            principal1.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
            principal1.show();

        }
    }//GEN-LAST:event_jProveedoresActionPerformed

    private void rptEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptEmpleadosActionPerformed
        queryEmpleados qe = new queryEmpleados();
        qe.reporteEmpleados();
    }//GEN-LAST:event_rptEmpleadosActionPerformed

    private void rptProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptProveedoresActionPerformed
       queryProveedores qe = new queryProveedores();
       qe.reporteProveedores();
        
    }//GEN-LAST:event_rptProveedoresActionPerformed

    private void jClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientesActionPerformed
        ClienteSearch obj = new ClienteSearch();
        HomeAplicativo.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();
    }//GEN-LAST:event_jClientesActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        this.dispose();
        InicioAplicativo login = new InicioAplicativo();
        login.setVisible(true);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAcercaDeActionPerformed
        Acerca obj = new Acerca();
        HomeAplicativo.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();
    }//GEN-LAST:event_jAcercaDeActionPerformed

    private void mAgregar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAgregar3ActionPerformed
        UsuariosNew obj = new UsuariosNew();
        HomeAplicativo.escritorio.add(obj);
        obj.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = obj.getSize();
        obj.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        obj.show();
        
    }//GEN-LAST:event_mAgregar3ActionPerformed

    private void mModificar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mModificar3ActionPerformed
        
        UsuariosEdit editUsuarios = new UsuariosEdit();
        HomeAplicativo.escritorio.add(editUsuarios);
        editUsuarios.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = editUsuarios.getSize();
        editUsuarios.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        editUsuarios.show();
        
    }//GEN-LAST:event_mModificar3ActionPerformed

    private void mEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEliminar3ActionPerformed
        
        UsuariosDelete deleteUsuarios = new UsuariosDelete();
        HomeAplicativo.escritorio.add(deleteUsuarios);
        deleteUsuarios.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = deleteUsuarios.getSize();
        deleteUsuarios.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        deleteUsuarios.show();
        
    }//GEN-LAST:event_mEliminar3ActionPerformed

    private void mConsultar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultar3ActionPerformed
         
        UsuariosSearch searchUsuarios = new UsuariosSearch();
        HomeAplicativo.escritorio.add(searchUsuarios);
        searchUsuarios.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = searchUsuarios.getSize();
        searchUsuarios.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        searchUsuarios.show();
        
        
    }//GEN-LAST:event_mConsultar3ActionPerformed

    private void prodAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodAgregarActionPerformed
        ArticulosNew newArticulos = new ArticulosNew();
        HomeAplicativo.escritorio.add(newArticulos);
        newArticulos.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = newArticulos.getSize();
        newArticulos.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        newArticulos.show();
    }//GEN-LAST:event_prodAgregarActionPerformed

    private void prodModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodModificarActionPerformed
        ArticulosUpdate updateArticulos = new ArticulosUpdate();
        HomeAplicativo.escritorio.add(updateArticulos);
        updateArticulos.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = updateArticulos.getSize();
        updateArticulos.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        updateArticulos.show();
    }//GEN-LAST:event_prodModificarActionPerformed

    private void prodConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodConsultarActionPerformed
        BusquedaArticulos buscarArticulos = new BusquedaArticulos();
        HomeAplicativo.escritorio.add(buscarArticulos);
        buscarArticulos.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = buscarArticulos.getSize();
        buscarArticulos.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        buscarArticulos.show();
    }//GEN-LAST:event_prodConsultarActionPerformed

    private void IvaNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IvaNewActionPerformed
        IvaNew newIva = new IvaNew();
        HomeAplicativo.escritorio.add(newIva);
        newIva.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = newIva.getSize();
        newIva.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        newIva.show();
    }//GEN-LAST:event_IvaNewActionPerformed

    private void IvaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IvaEditActionPerformed
        IvaEditar editIva = new IvaEditar();
        HomeAplicativo.escritorio.add(editIva);
        editIva.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = editIva.getSize();
        editIva.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        editIva.show();
    }//GEN-LAST:event_IvaEditActionPerformed

    private void IvaSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IvaSearchActionPerformed
        IvaLeer leerIva = new IvaLeer();
        HomeAplicativo.escritorio.add(leerIva);
        leerIva.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = leerIva.getSize();
        leerIva.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        leerIva.show();
    }//GEN-LAST:event_IvaSearchActionPerformed

    private void FamiNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamiNewActionPerformed
        FamiliasNew newFamilias = new FamiliasNew();
        HomeAplicativo.escritorio.add(newFamilias);
        newFamilias.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = newFamilias.getSize();
        newFamilias.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        newFamilias.show();
    }//GEN-LAST:event_FamiNewActionPerformed

    private void FamiEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamiEditActionPerformed
        FamiliasUpdate updateFamilias = new FamiliasUpdate();
        HomeAplicativo.escritorio.add(updateFamilias);
        updateFamilias.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = updateFamilias.getSize();
        updateFamilias.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        updateFamilias.show();
    }//GEN-LAST:event_FamiEditActionPerformed

    private void FamiSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FamiSearchActionPerformed
        FamiliasBuscar buscarFamilias = new FamiliasBuscar();
        HomeAplicativo.escritorio.add(buscarFamilias);
        buscarFamilias.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = buscarFamilias.getSize();
        buscarFamilias.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        buscarFamilias.show();
    }//GEN-LAST:event_FamiSearchActionPerformed

    private void venNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_venNuevaActionPerformed
       VentasNew newVentas = new VentasNew();
        HomeAplicativo.escritorio.add(newVentas);
        newVentas.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = newVentas.getSize();
        newVentas.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        newVentas.show();     
    }//GEN-LAST:event_venNuevaActionPerformed

    private void CuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuentaActionPerformed
        UsuariosCuenta cuentaUsuarios = new UsuariosCuenta(lblCuenta.getText(), lblNivel.getText());
        HomeAplicativo.escritorio.add(cuentaUsuarios);
        cuentaUsuarios.toFront();
        //centrar
        //Para centrar la ventana abierta
        Dimension dimension = escritorio.getSize();
        Dimension FrameSize = cuentaUsuarios.getSize();
        cuentaUsuarios.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
        //
        cuentaUsuarios.show();
    }//GEN-LAST:event_CuentaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        try {
            VentasView viewVentas = new VentasView();
            HomeAplicativo.escritorio.add(viewVentas);
            viewVentas.toFront();
            //centrar
            //Para centrar la ventana abierta
            Dimension dimension = escritorio.getSize();
            Dimension FrameSize = viewVentas.getSize();
            viewVentas.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
            //
            viewVentas.show();
        } catch (ParseException ex) {
            Logger.getLogger(HomeAplicativo.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        queryProductos queryProduct = new queryProductos();
        queryProduct.reportePrductosMasV();
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        queryProductos queryProduct = new queryProductos();
        queryProduct.reportePrductosMenosV();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAplicativo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAplicativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cuenta;
    private javax.swing.JMenuItem FamiEdit;
    private javax.swing.JMenuItem FamiNew;
    private javax.swing.JMenuItem FamiSearch;
    private javax.swing.JMenuItem IvaEdit;
    private javax.swing.JMenuItem IvaNew;
    private javax.swing.JMenuItem IvaSearch;
    private javax.swing.JMenu Ivas;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jAcercaDe;
    private javax.swing.JMenuItem jClientes;
    private javax.swing.JMenu jConfiguracion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuItem jEmpleados;
    private javax.swing.JMenu jInicio;
    private javax.swing.JMenu jInventarios;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jProductos;
    private javax.swing.JMenuItem jProveedores;
    private javax.swing.JMenu jReportes;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jUsuarios;
    private javax.swing.JMenu jVentas;
    public static javax.swing.JLabel lblCuenta;
    public javax.swing.JLabel lblNivel;
    private javax.swing.JMenuItem mAgregar3;
    private javax.swing.JMenuItem mConsultar3;
    private javax.swing.JMenuItem mEliminar3;
    private javax.swing.JMenuItem mModificar3;
    private javax.swing.JMenu mbUsuarios;
    private javax.swing.JMenuItem prodAgregar;
    private javax.swing.JMenuItem prodConsultar;
    private javax.swing.JMenuItem prodModificar;
    private javax.swing.JMenuItem rptEmpleados;
    private javax.swing.JMenuItem rptProveedores;
    private javax.swing.JMenuItem venNueva;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the cuenta
     */
    public static String getCuenta() {
        return cuenta;
    }

    /**
     * @param aCuenta the cuenta to set
     */
    public static void setCuenta(String aCuenta) {
        cuenta = aCuenta;
    }

    /**
     * @return the nivel
     */
    public static String getNivel() {
        return nivel;
    }

    /**
     * @param aNivel the nivel to set
     */
    public static void setNivel(String aNivel) {
        nivel = aNivel;
    }
    
    
    public static String getCuenta1() {
        return lblCuenta.getText();
    }
}
