/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaEmpleado;

import MODELO.queryEmpleados;
import VistaEmpleado.DatosEmpleados;
import Vista.HomeAplicativo;
import static Vista.HomeAplicativo.escritorio;
import java.awt.Dimension;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Roger
 */
public class EmpleadoPrincipal1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuariosNew
     */
    queryEmpleados queryE = new queryEmpleados();
    private TableRowSorter trsFiltro;

    public EmpleadoPrincipal1() {

        initComponents();
        queryE.listarTodosEmpleados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelBuscado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListarEmpleado = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jCmbTipoBusqueda = new javax.swing.JComboBox<>();
        jTextFieldParametroBusqueda = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/equipo.png"))); // NOI18N
        jLabel1.setText("Empleados");

        btnVolver.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar.png"))); // NOI18N
        btnVolver.setText("VOLVER");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lista-de-usuario.png"))); // NOI18N

        jLabelBuscado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBuscado.setText("Código:");

        jTableListarEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableListarEmpleado);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Buscar por:");

        jCmbTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Identificador", "Nombre", "Apellido" }));
        jCmbTipoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbTipoBusquedaActionPerformed(evt);
            }
        });

        jTextFieldParametroBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldParametroBusquedaKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldParametroBusquedaKeyPressed(evt);
            }
        });

        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrear.setText("CREAR");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnVer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVer.setText("VER");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEliminar.setText("ELMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabelBuscado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCmbTipoBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldParametroBusqueda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(216, 216, 216)
                                .addComponent(jLabel6))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrear)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jCmbTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar)
                            .addComponent(btnEditar)
                            .addComponent(btnVer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelBuscado)
                            .addComponent(jTextFieldParametroBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addComponent(btnVolver)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jCmbTipoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbTipoBusquedaActionPerformed
        if (jCmbTipoBusqueda.getSelectedIndex() == 0) {
            jLabelBuscado.setText("Codigo");
        }
        if (jCmbTipoBusqueda.getSelectedIndex() == 1) {
            jLabelBuscado.setText("Identificador");
        }
        if (jCmbTipoBusqueda.getSelectedIndex() == 2) {
            jLabelBuscado.setText("Nombre");
        }
        if (jCmbTipoBusqueda.getSelectedIndex() == 3) {
            jLabelBuscado.setText("Apellido");
        }
    }//GEN-LAST:event_jCmbTipoBusquedaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       this.dispose();
        
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jTextFieldParametroBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusquedaKeyPressed

    }//GEN-LAST:event_jTextFieldParametroBusquedaKeyPressed

    private void jTextFieldParametroBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParametroBusquedaKeyTyped
        jTextFieldParametroBusqueda.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String datos = (jTextFieldParametroBusqueda.getText().toUpperCase());
                jTextFieldParametroBusqueda.setText(datos);
                repaint();
                Filtrar();
            }
        });
        trsFiltro = new TableRowSorter(jTableListarEmpleado.getModel());
        jTableListarEmpleado.setRowSorter(trsFiltro);
    }//GEN-LAST:event_jTextFieldParametroBusquedaKeyTyped

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        try {
            DatosEmpleados datos = new DatosEmpleados();        

            datos.setOpcion(1);

            HomeAplicativo.escritorio.add(datos);
            datos.toFront();
            //Para centrar la ventana abierta
            Dimension dimension = escritorio.getSize();
            Dimension FrameSize = datos.getSize();
            datos.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
            //
            datos.setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            Logger.getLogger(EmpleadoPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            DatosEmpleados datos = new DatosEmpleados();
            if (jTableListarEmpleado.getSelectedRows().length > 0) {
                
                datos.setOpcion(2);
                HomeAplicativo.escritorio.add(datos);
                datos.toFront();
                //Para centrar la ventana abierta
                Dimension dimension = escritorio.getSize();
                Dimension FrameSize = datos.getSize();
                datos.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
                //
                
                String cod = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 0).toString();
                String ident = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 1).toString();
                String nombres = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 2).toString();
                String apellidos = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 3).toString();
                String direccion = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 4).toString();
                String telefono = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 5).toString();
                String cargo = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 6).toString();
                //String observacion = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 7).toString();
                String observacion="";
                String fnacimiento = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 7).toString();
                String fingreso = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 8).toString();

                try {
                    datos.Llenar(cod, ident, nombres, apellidos, direccion, telefono, cargo, observacion, fnacimiento, fingreso);
                } catch (ParseException ex) {
                    Logger.getLogger(EmpleadoPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
                }
                datos.setVisible(true);
                //this.dispose();
            
            }
        } catch (ParseException ex) {
            Logger.getLogger(EmpleadoPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (jTableListarEmpleado.getSelectedRows().length > 0) {
            queryEmpleados queryE = new queryEmpleados();
            int code = Integer.parseInt(jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 0).toString());
            queryE.eliminarEmpleado(code);
            queryE.actualizarTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        try {
            DatosEmpleados datos = new DatosEmpleados();
            if (jTableListarEmpleado.getSelectedRows().length > 0) {
                if (!datos.isShowing()) {
                    
                    datos.setOpcion(3);
                    HomeAplicativo.escritorio.add(datos);
                    datos.toFront();
                    //Para centrar la ventana abierta
                    Dimension dimension = escritorio.getSize();
                    Dimension FrameSize = datos.getSize();
                    datos.setLocation((dimension.width - FrameSize.width) / 2, (dimension.height - FrameSize.height) / 2);
                    //
                    String cod = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 0).toString();
                    String ident = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 1).toString();
                    String nombres = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 2).toString();
                    String apellidos = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 3).toString();
                    String direccion = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 4).toString();
                    String telefono = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 5).toString();
                    String cargo = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 6).toString();
                    //String observacion = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 7).toString();
                    String observacion="";
                    String fnacimiento = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 7).toString();
                    String fingreso = jTableListarEmpleado.getValueAt(jTableListarEmpleado.getSelectedRow(), 8).toString();
                    
                    try {
                        datos.Llenar(cod, ident, nombres, apellidos, direccion, telefono, cargo, observacion, fnacimiento, fingreso);
                        datos.Deshabilitar();
                    } catch (ParseException ex) {
                        Logger.getLogger(EmpleadoPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    datos.setVisible(true);
                    this.dispose();
                }
            }
        } catch (ParseException ex) {
            Logger.getLogger(EmpleadoPrincipal1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVerActionPerformed
    public void Filtrar() {

        int columnaABuscar = 0;

        if (jCmbTipoBusqueda.getSelectedItem() == "Código") {
            columnaABuscar = 0;
        }
        if (jCmbTipoBusqueda.getSelectedItem() == "Identificador") {
            columnaABuscar = 1;
        }
        if (jCmbTipoBusqueda.getSelectedItem() == "Nombre") {
            columnaABuscar = 2;
        }
        if (jCmbTipoBusqueda.getSelectedItem() == "Apellido") {
            columnaABuscar = 3;
        }
        trsFiltro.setRowFilter(RowFilter.regexFilter("(?i)" + jTextFieldParametroBusqueda.getText(), columnaABuscar));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> jCmbTipoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelBuscado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableListarEmpleado;
    private javax.swing.JTextField jTextFieldParametroBusqueda;
    // End of variables declaration//GEN-END:variables
}
